### PR TITLE
Compatibility with low memory addresses

### LINKED ISSUE #397: Streaming decompression issue w/emscripten
Hi,

I'm porting the [blockStreaming_ringBuffer.c](https://github.com/lz4/lz4/blob/dev/examples/blockStreaming_ringBuffer.c) example to emscripten and I've run into an issue. I've tried to get to the bottom of it, here is my analysis, which could be completely wrong...

Because the address space is not shared and there is no OS in memory, `decBuf` happens to be allocated at a low address (say 0x159c). At some point the dictionary grows to 9216 bytes. Now `lowLimit` gets to be negative [here](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L1131). Because the pointer is unsigned, it becomes something like 0xfffff19c (emscripten is 32-bit). Now [this condition](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L1187) will trigger always (practically speaking) because it is an unsigned comparison. 💥 

The following patch appears to fix it:

```diff
diff --git a/lib/lz4.c b/lib/lz4.c
index 96422f8..7f48e36 100644
--- a/lib/lz4.c
+++ b/lib/lz4.c
@@ -1128,7 +1128,6 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
     BYTE* const oend = op + outputSize;
     BYTE* cpy;
     BYTE* oexit = op + targetOutputSize;
-    const BYTE* const lowLimit = lowPrefix - dictSize;
 
     const BYTE* const dictEnd = (const BYTE*)dictStart + dictSize;
     const unsigned dec32table[] = {0, 1, 2, 1, 4, 4, 4, 4};
@@ -1184,7 +1183,7 @@ LZ4_FORCE_INLINE int LZ4_decompress_generic(
         /* get offset */
         offset = LZ4_readLE16(ip); ip+=2;
         match = op - offset;
-        if ((checkOffset) && (unlikely(match < lowLimit))) goto _output_error;   /* Error : offset outside buffers */
+        if ((checkOffset) && (unlikely(match + dictSize < lowPrefix))) goto _output_error;   /* Error : offset outside buffers */
         LZ4_write32(op, (U32)offset);   /* costs ~1%; silence an msan warning when offset==0 */
 
         /* get matchlength */
```

I'm not sure whether similar calculations in other parts of the code (e.g. [here](https://github.com/lz4/lz4/blob/1ad9a36cfb9fc669b0b18bfcd902d3e52a3d2cbb/lib/lz4.c#L517)) are unaffected or whether they work for me only because the buffer happens to be at a high enough address.

### PR DESCRIPTION
**Pull request by Cyan4973**
Current lz4 fast compression implementation has a weakness
when input buffer is provided at a low memory address < 64K.

Several checks are performed as pointer comparisons, but their result depend on the condition that input memory address is > 64K, which is true on most systems.

This patch makes lz4 compatible with low memory addresses.
It adds a test (within `fuzzer`) to generate and test such condition, as part of CI suite.

The patch protects `byU32` mode against such scenario, by making checks based on index values, instead of pointers. This also remove a ptr overflow check, which is known to cause trouble on some IBM systems (see #485).
`byPtr` mode still needs pointer comparisons. It is only available for 32-bits systems, and when there is no dictionary and no streaming. It is now also restricted to buffers starting >= address 64KB. When any of these conditions is not respected, the implementation switches to `byU32`.

Should fix #397 , #463 and #485.

### CODE REVIEW

**Comment by terrelln** [comment]
Looks like you accidentally? changed your git name.

File: lib/lz4hc.c [hunk 1]
```diff
@@ -885,7 +886,7 @@ char* LZ4_slideInputBufferHC(void* LZ4HC_Data)
 {
     LZ4HC_CCtx_internal* const hc4 = &((LZ4_streamHC_t*)LZ4HC_Data)->internal_donotuse;
     int const dictSize = LZ4_saveDictHC((LZ4_streamHC_t*)LZ4HC_Data, (char*)(hc4->inputBuffer), 64 KB);
-    return (char*)(hc4->inputBuffer + dictSize);
+    return (char*)(hc4->inputBuffer) + dictSize;
```
Comment (terrelln) [inline lib/lz4hc.c]: Should it return a `const char*`, or do we not want to change the API?

File: lib/lz4.c [hunk 2]
```diff
@@ -773,34 +846,66 @@ LZ4_FORCE_INLINE int LZ4_compress_generic(
         /* Fill table */
         LZ4_putPosition(ip-2, cctx->hashTable, tableType, base);
 
+#if 1
```
Comment (terrelln) [inline lib/lz4.c]: Is there a reason to leave the `#if 1` around?

File: lib/lz4.c [hunk 3]
```diff
@@ -721,30 +783,41 @@ LZ4_FORCE_INLINE int LZ4_compress_generic(
             /* Copy Literals */
             LZ4_wildCopy(op, anchor, op+litLength);
             op+=litLength;
+            DEBUGLOG(6, "seq.start:%zi, literals=%u, match.start:%zi", anchor-(const BYTE*)source, litLength, ip-(const BYTE*)source);
         }
 
 _next_match:
```
Comment (terrelln) [inline lib/lz4.c]: Can we list the variables required by `_next_match` in a comment?

**Comment by Cyan4973** [comment]
> Looks like you accidentally? changed your git name.

Right, I had to develop this patch on a Linux VM in order to access capability to generate buffer at low memory addresses. Since it's a new system, it has different settings.

To be fixed...

File: lib/lz4hc.c (hunk 1 above)
Comment (Cyan4973) [reply lib/lz4hc.c]: It must return a non-`const` pointer, since it is the position at which user is supposed to resume filling the buffer with some new input.

It's a pretty poor interface, and that's why it is deprecated.

File: lib/lz4.c (hunk 2 above)
Comment (Cyan4973) [reply lib/lz4.c]: I was making some speed comparison tests.
You're right, it shall be removed before merge.

Comment (terrelln) [reply lib/lz4.c]: I've tried removing it as well, but it was a pretty large loss for me, though I don't remember the exact numbers, maybe 5%.

Comment (Cyan4973) [reply lib/lz4.c]: yes, I had about the same experience

**Comment by Cyan4973** [comment]
The speed regression was introduced in 64a3e41acaf9e186937d32c9dd2dc104e5bc4a72.

It's important to note that previous patch, 6d931b6a93100fe2cb4dafc032ff486c814d1fed, wasn't correct, as it could not support "advanced" scenarios.
But for the straighforward `lz4 -b` scenario, it would work correctly, and introduce no speed regression.

It might be that 64a3e41acaf9e186937d32c9dd2dc104e5bc4a72 introduced too many changes in a single patch, as the goal was to support remaining scenarios. But the result is that it's difficult to associate the speed regression to one specific element.

So maybe a possible solution is to restart from 6d931b6a93100fe2cb4dafc032ff486c814d1fed, and introduce changes slowly, to see which one trigger any speed regression.
